In [1]:
import numpy as np

In [2]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [3]:
np.ones((5,), dtype=int)

array([1, 1, 1, 1, 1])

In [4]:
np.ones((2, 1))

array([[1.],
       [1.]])

In [5]:
s = (2,2)
np.ones(s)

array([[1., 1.],
       [1., 1.]])